### ISSUE TITLE
clusterForDatabase Session request 

### ISSUE THREAD

**Issue by ezhulkov** [leanovate/play-cassandra-evolutions#1]
Hi! thank you for your awesome lib

How do you think, is it a good idea to change return type of clusterForDatabase to Session? 
It gives you additional flexibility to specify working keyspace via cluster.connect(keyspace)

For example, I have 3 environments - dev, test and prod and 1 cassandra cluster. I want to be able to store my data in 3 different keyspaces on this cluster - data_dev, data_test and data_prod. 

If clusterForDatabase returned Session I would be able to call cluster.connect('data_dev') and evolutions would be applied to this keyspace only.

With the current approach it looks a liitle bit ugly - I create cluster wrapper and force it to return keyspace biased sessions only

``` scala
override def clusterForDatabase(db: String): Cluster = new BiasedCluster('data_dev', cluster)
class BiasedCluster(val keyspace: String, val cluster: Cluster) extends Cluster(null, null, null) {
    override def connect(): Session = connect(this.keyspace)
    override def connect(keyspace: String): Session = super.connect(this.keyspace)
}
```

**Comment by untoldwind** [comment]
Hi,

just did a downward compatible refactoring. Current snapshot should be available via the OSS repo.
If this solves your problem, I'll create a release of this version

**Comment by ezhulkov** [comment]
Got stuck on another problem - you create meta keyspace with fixed name DBNAME_evolutions, where DBNAME is a logical name of database but not a keyspace name.
Having several keyspaces with one logical name leads to collision. 
Any ideas how to fix it?

UPD: is it a good idea to add one more function evolutionKeyspaceForDatabase?

**Comment by untoldwind** [comment]
I think that's a fair enough compromise.
The current version should be still backward compatible and allow the flexibility you need

**Comment by ezhulkov** [comment]
This is exactly what I was looking for! Thank you and waiting for release

**Comment by untoldwind** [comment]
Just pushed 2.5.1 to maven central ... will be visible in search in an hour or so
